//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Customer = new HashSet<Customer>();
            this.Product = new HashSet<Product>();
        }
    
        public decimal Order_id { get; set; }
        public string Order_description { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
